### ISSUE TITLE
unitialized constant, Shef (NameError)

### ISSUE THREAD

**Issue by halfinhalfout** [jbz/knife-audit#8]
knife audit always gives "audit.rb:121:in `run': uninitialized constant KnifeAudit::Audit::Shef (NameError)":

Errors here: https://github.com/jbz/knife-audit/blob/master/lib/chef/knife/audit.rb#L121

eg.,
knife audit xslt -VV
...
DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
/Users/dwilson/.rvm/gems/ruby-1.9.3-p545@chef/gems/knife-audit-0.2.0/lib/chef/knife/audit.rb:121:in `run': uninitialized constant KnifeAudit::Audit::Shef (NameError)
    from /Users/dwilson/.rvm/gems/ruby-1.9.3-p545@chef/gems/chef-11.12.8/lib/chef/knife.rb:492:in`run_with_pretty_exceptions'
    from /Users/dwilson/.rvm/gems/ruby-1.9.3-p545@chef/gems/chef-11.12.8/lib/chef/knife.rb:174:in `run'
    from /Users/dwilson/.rvm/gems/ruby-1.9.3-p545@chef/gems/chef-11.12.8/lib/chef/application/knife.rb:135:in`run'
    from /Users/dwilson/.rvm/gems/ruby-1.9.3-p545@chef/gems/chef-11.12.8/bin/knife:25:in `<top (required)>'
    from /Users/dwilson/.rvm/gems/ruby-1.9.3-p545@chef/bin/knife:23:in`load'
    from /Users/dwilson/.rvm/gems/ruby-1.9.3-p545@chef/bin/knife:23:in `<main>'
    from /Users/dwilson/.rvm/gems/ruby-1.9.3-p545@chef/bin/ruby_executable_hooks:15:in`eval'
    from /Users/dwilson/.rvm/gems/ruby-1.9.3-p545@chef/bin/ruby_executable_hooks:15:in `<main>'

Running chef version 11.12.8:
helpdesksmbp94:chef-hosted dwilson$ gem list chef --local

**\* LOCAL GEMS ***

chef (11.12.8)
chef-zero (2.0.2)
chefspec (4.0.1, 3.4.0, 2.0.1)
minitest-chef-handler (1.0.2, 1.0.1)
helpdesksmbp94:chef-hosted dwilson$

Any ideas?

**Comment by mrjcleaver** [comment]
+1 !

**Comment by tarak** [comment]
+1
